name: "🐛 Bug Report"
description: if you have discovered an issue you can report it here.
labels: [
  "bug", "TRIAGE"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: "Code"
      description: A minimum reproducible example, see https://stackoverflow.com/help/minimal-reproducible-example
      value: |
        import ...
      render: python3
    validations:
      required: false
  - type: textarea

    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: textarea
    id: requirements
    attributes:
      label: "Requirements"
      description: Please list the requirements needed including version numbers
      value: |
        xyz
      render: bash
    validations:
      required: false